### ISSUE TITLE
Wizard animation

### ISSUE THREAD

**Issue by balsigergil** [GameTechHes/Sapphire#34]
Le magicien n'est pas correctement animé

**Comment by Mathistis** [comment]
Normalement c'est good

**Comment by Mathistis** [comment]
Il faut stop l'animation quand le magicien saute !

**Comment by Mathistis** [comment]
Normalement tout marche sauf l'annimation saut qui est bug (j'ai l'impression que elle se lance pas si IDLE est pas fini)
