### ISSUE TITLE
Sapphire sont incrémentés 2 fois

### ISSUE THREAD

**Issue by balsigergil** [GameTechHes/Sapphire#45]
Bug de réseau probablement dans le script PowerUpSapphire.cs

**Comment by Obyka** [comment]
Chez moi le Sapphire ne s'incrémente qu'une fois

**Comment by Obyka** [comment]
Seul le joueur qui REJOINT ramasse 2 Sapphire

**Comment by Obyka** [comment]
Est-ce par ce que chaque joueur possède son propre SapphireController ?
